// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Models;

public partial class Empresa
{
    [Key]
    [StringLength(18)]
    [Unicode(false)]
    public string CNPJ { get; set; }

    [Required]
    [StringLength(450)]
    public string UserId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [InverseProperty("CNPJ_EmpresaNavigation")]
    public virtual ICollection<Avaliacao> Avaliacao { get; set; } = new List<Avaliacao>();

    [InverseProperty("CNPJ_EmpresaNavigation")]
    public virtual ICollection<Vaga> Vaga { get; set; } = new List<Vaga>();
}