// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Models;

public partial class Vaga
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(18)]
    [Unicode(false)]
    public string CNPJ_Empresa { get; set; }

    [Required]
    [StringLength(400)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [StringLength(400)]
    [Unicode(false)]
    public string Requisitos { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AreaAtuacao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Modelo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Localizacao { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TipoContrato { get; set; }

    public DateOnly? DataInicio { get; set; }

    public DateOnly? DataFim { get; set; }

    [ForeignKey("CNPJ_Empresa")]
    [InverseProperty("Vaga")]
    public virtual Empresa CNPJ_EmpresaNavigation { get; set; }
}